FROM openjdk:11 as builder

ARG BRANCH
ARG GIT_FORK

ENV BRANCH=${BRANCH:-master-tabdebug-old}
ENV GIT_FORK=${GIT_FORK:-https://github.com/Bouncheck/scylla-tools-java}

RUN git clone -b ${BRANCH} --single-branch ${GIT_FORK}
RUN apt -y update && apt-get -y install ant

# build
RUN cd scylla-tools-java && ant


FROM openjdk:11 as app

COPY --from=builder /scylla-tools-java /scylla-tools-java

WORKDIR /scylla-tools-java

RUN bash ./SCYLLA-VERSION-GEN \
    && cp build/SCYLLA-* . \
    && ./install.sh

# hack, cause in some versions not all the files are handled by install.sh
RUN find . -iname *.jar | xargs -I{}  cp {} /opt/scylladb/share/cassandra/lib/
